[project]
name = "water-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "openpyxl>=3.1.5",
    "pytest>=8.3.5",
    "rich>=14.2.0",
    "taos-ws-py>=0.3.9",
    "taospy>=2.7.21",
    "uvicorn[standard]>=0.34.0",
]
